---
# For use with pre-commit.
# See usage instructions at https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-toml
      stages: [pre-commit]
    - id: check-yaml
      stages: [pre-commit]
    - id: check-merge-conflict
      stages: [pre-commit]
    - id: check-case-conflict
      stages: [pre-commit]
    - id: detect-private-key
      stages: [pre-commit]
    - id: mixed-line-ending
      stages: [pre-commit]
      args: ["--fix=lf"]
    - id: trailing-whitespace
      stages: [pre-commit]
      args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/crate-ci/committed
    rev: v1.0.20
    hooks:
    - id: committed
      stages: [commit-msg]
  # cspell is dictionary based
  # Dictionary: A confidence rating is given for how close a word is to one in a dictionary
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.3.0
    hooks:
    - id: cspell
  # typos is corrections based
  # Corrections: Known misspellings that map to their corresponding dictionary word
  - repo: https://github.com/crate-ci/typos
    rev: v1.18.2
    hooks:
    - id: typos
      pass_filenames: false
      args: [] # this prevents typos from being autocorrected (so you have a chance to review them)
  - repo: local
    hooks:
    - id: cargo-fmt
      name: cargo fmt
      description: Run cargo fmt
      entry: cargo fmt
      language: system
      types: [rust]
      args: ["--"]
      require_serial: true
    - id: cargo-clippy
      name: cargo clippy
      description: Run cargo clippy
      entry: cargo clippy
      language: system
      types: [rust]
      pass_filenames: false
      args: ["--all-features", "--", "-D", "warnings", "-A", "unknown-lints"]
    - id: cargo-test
      name: cargo test
      description: Run cargo test
      entry: cargo test
      language: system
      types: [rust]
      pass_filenames: false
      args: ["--all-features", "--"]
