name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hook: [ check-toml,
                check-yaml,
                check-merge-conflict,
                check-case-conflict,
                detect-private-key,
                mixed-line-ending,
                trailing-whitespace,
                cspell,
                typos,
                cargo-fmt,
                cargo-clippy,
                cargo-test,
              ]
    steps:
    - name: Get required packages
      run: sudo apt-get install libsensors-dev libssl-dev libpulse-dev libnotmuch-dev
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: ${{ matrix.hook }} --all-files


